version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
    language: java
    jdk:
      - oraclejdk7
    script:
      - javac PositionTest
      - java -classpath junit.jar PositionTest
